-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."player_quest_log" add column "is_reward_claimed" boolean
--  not null default 'false';
